application: mc-coal
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /api/.*
  script: api.application

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
