application: mc-coal
version: 1
runtime: python27
threadsafe: true
api_version: 1

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: latest

builtins:
- remote_api: on
- deferred: on

inbound_services:
- warmup
- channel_presence

handlers:
- url: /_ah/warmup
  script: warmup.application

- url: /_ah/channel/.*
  script: channel.application

# - url: /google28fe702d4ac094cf\.html
#   static_files: google28fe702d4ac094cf.html
#   upload: google28fe702d4ac094cf.html

- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/(.*)

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /sounds
  static_dir: static/sounds

- url: /js
  static_dir: static/js

- url: /cron/.*
  script: cron.application
  login: admin

- url: /api/.*
  script: api.application

- url: /.*
  script: main.application
